//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demex
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string Code { get; set; }
        public int Id_Service { get; set; }
        public int Id_Patient { get; set; }
        public Nullable<System.DateTime> DateSucces { get; set; }
        public int IdUsers { get; set; }
    
        public virtual DateOfPatients DateOfPatients { get; set; }
        public virtual Service Service { get; set; }
        public virtual Users Users { get; set; }
    }
}
